[package]
name = "dawremi"
version = "0.1.0"
authors = ["guimcaballero <guim.caballero@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "crates/*",
]

[dependencies]
anyhow = "1.0.34"

dawremi_core = { path = "./crates/dawremi_core" }

[features]
metronome = []
