[package]
name = "dawremi_debug"
version = "0.1.0"
authors = ["guimcaballero <guim.caballero@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dawremi_core = { path = "../dawremi_core" }
open = "1.6.0"
